-- 코드를 입력하세요
SELECT TITLE,  b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, "%Y-%m-%d") 
as CREATED_DATE
FROM USED_GOODS_BOARD b join USED_GOODS_REPLY r on b.BOARD_ID = r.BOARD_ID
WHERE b.CREATED_DATE < "2022-11-01" and b.CREATED_DATE > "2022-9-30"
ORDER BY r.CREATED_DATE asc, b.TITLE asc